name = "linkedin-newsletter-rss"
main = "index.js"
compatibility_date = "2023-11-09"
workers_dev = true
node_compat = true

route = { pattern = "linkedinrss.cns.me/*", zone_name = "cns.me" }

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
